apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: squid-exporter-service
spec:
  selector:
    app: squid-exporter
  ports:
  - protocol: TCP
    port: 9301
    targetPort: 9301
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: squid-exporter-deployment
  labels:
    app: squid-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid-exporter
  template:
    metadata:
      labels:
        app: squid-exporter
    spec:
      containers:
      - name: squid-exporter
        image: boynux/squid-exporter
        ports:
        - containerPort: 9301
        env:
        - name: SQUID_HOSTNAME
          value: "forward-proxy"
        - name: SQUID_PORT
          value: "80"
        - name: SQUID_EXPORTER_LISTEN
          value: "0.0.0.0:9301"
