apiVersion: v1
kind: Service
metadata:
  name: forward-proxy
  labels:
    app: forward-proxy
spec:
  ports:
    - port: 80
  selector:
    app: forward-proxy
    tier: backend
  type: NodePort  
---
apiVersion: apps/v1        
kind: Deployment
metadata:
  name: forward-proxy 
  labels:
    app: forward-proxy
spec:
  selector:
    matchLabels:
      app: forward-proxy
      tier: backend       
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: forward-proxy
        tier: backend     
    spec:
      containers:
      - image: sameersbn/squid
        name: forward-proxy
        ports:
        - containerPort: 80
          name: forward-proxy
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /etc/squid3/squid.conf
          name: proxy-conf
          subPath: default.conf
      volumes:
      - configMap:
          defaultMode: 420
          name: proxy-map-conf
        name: proxy-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-map-conf
data:
  default.conf: |
    http_port 80

    refresh_pattern ^ftp:           1440    20%     10080
    refresh_pattern ^gopher:        1440    0%      1440
    refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
    refresh_pattern .               0       20%     4320

    acl localnet src 10.0.0.0/8     # RFC 1918 possible internal network
    acl localnet src 172.16.0.0/12  # RFC 1918 possible internal network
    acl localnet src 192.168.0.0/16 # RFC 1918 possible internal network
    acl localnet src fc00::/7       # RFC 4193 local private network range
    acl localnet src fe80::/10      # RFC 4291 link-local (directly plugged) machines
    acl all      src 0.0.0.0/0.0.0.0

    acl SSL_ports port 443          # https

    acl Safe_ports port 80          # http
    acl Safe_ports port 21          # ftp
    acl Safe_ports port 443         # https
    acl Safe_ports port 70          # gopher
    acl Safe_ports port 210         # wais
    acl Safe_ports port 1025-65535  # unregistered ports
    acl Safe_ports port 280         # http-mgmt
    acl Safe_ports port 488         # gss-http
    acl Safe_ports port 591         # filemaker
    acl Safe_ports port 777         # multiling http

    acl CONNECT method CONNECT

    http_access allow manager localhost
    http_access allow all
    http_access deny manager
    http_access deny !Safe_ports
    http_access deny CONNECT !SSL_ports
    http_access allow localhost
