apiVersion: v1
kind: Service
metadata:
  name: forward-proxy
  labels:
    app: forward-proxy
spec:
  ports:
    - port: 80
  selector:
    app: forward-proxy
    tier: backend
  type: NodePort  
---
apiVersion: apps/v1        
kind: Deployment
metadata:
  name: forward-proxy 
  labels:
    app: forward-proxy
spec:
  selector:
    matchLabels:
      app: forward-proxy
      tier: backend       
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: forward-proxy
        tier: backend     
    spec:
      containers:
      - image: nginx:1.21
        name: forward-proxy
        ports:
        - containerPort: 80
          name: forward-proxy
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: proxy-conf
          subPath: default.conf
      volumes:
      - configMap:
          defaultMode: 420
          name: proxy-map-conf
        name: proxy-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-map-conf
data:
  default.conf: |
    server {
      listen 80 default_server;
      server_name  _;
      
      location /metrics {
          stub_status on;
      }
      
      location / {
        resolver 8.8.8.8; # may or may not be necessary.
        proxy_pass http://$http_host$uri$is_args$args;
      }
    }
